"""
REFLEX Dashboard — Hub registry and compose file discovery.

Central registry of all platform hubs with their metadata.
This should eventually load from ports.yaml (Single Source of Truth).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

__all__ = ["COMPOSE_FILES", "HUBS", "find_compose_file"]
HUBS: list[dict[str, Any]] = [
    {
        "name": "Coach Hub",
        "slug": "coach-hub",
        "description": "Coaching platform — Assessments, QuickCheck, Maturity-Scoring.",
        "icon": "🎯",
        "color": "accent",
        "category": "product",
        "tags": ["Coaching", "SaaS"],
        "port": 8007,
        "container_name": "coach_hub_web",
        "prod_url": "https://kiohnerisiko.de",
        "sort_order": 5,
    },
    {
        "name": "Schutztat Risk Hub",
        "slug": "risk-hub",
        "description": "Gefährdungsbeurteilungen, Hazard-Analyse, Maßnahmen-Tracking.",
        "icon": "⚠️",
        "color": "red",
        "category": "product",
        "tags": ["Django Ninja", "SaaS"],
        "port": 8090,
        "container_name": "risk_hub_web",
        "prod_url": "https://schutztat.de",
        "sort_order": 10,
    },
    {
        "name": "BF Agent",
        "slug": "bfagent",
        "description": "Book Factory Agent — AI-powered creative writing and publishing.",
        "icon": "📚",
        "color": "purple",
        "category": "product",
        "tags": ["AI Agent"],
        "port": 8091,
        "container_name": "bfagent_web",
        "prod_url": "https://bfagent.iil.pet",
        "sort_order": 20,
    },
    {
        "name": "Writing Hub",
        "slug": "writing-hub",
        "description": "Buchreihen, Kapitel, Charaktere — Romane mit KI schreiben.",
        "icon": "✍️",
        "color": "amber",
        "category": "product",
        "tags": ["Writing", "AI"],
        "port": 8097,
        "container_name": "writing_hub_web",
        "prod_url": "https://writing.iil.pet",
        "sort_order": 25,
    },
    {
        "name": "DriftTales",
        "slug": "travel-beat",
        "description": "AI-generated travel stories with smart location enrichment.",
        "icon": "✈️",
        "color": "cyan",
        "category": "product",
        "tags": ["Travel"],
        "port": 8089,
        "container_name": "travel_beat_web",
        "prod_url": "https://drifttales.app",
        "sort_order": 30,
    },
    {
        "name": "Weltenforger",
        "slug": "weltenhub",
        "description": "Story universe platform — world-building and narrative design.",
        "icon": "🌐",
        "color": "pink",
        "category": "product",
        "tags": ["Creative"],
        "port": 8081,
        "container_name": "weltenhub_web",
        "prod_url": "https://weltenforger.com",
        "sort_order": 35,
    },
    {
        "name": "137herz",
        "slug": "137-hub",
        "description": "Das Erwachen — Community Hub, Newsletter und Supersystem Chatbot.",
        "icon": "🔮",
        "color": "purple",
        "category": "product",
        "tags": ["Community", "AI"],
        "port": 8095,
        "container_name": "hub137_web",
        "prod_url": "https://137herz.de",
        "sort_order": 40,
    },
    {
        "name": "Wedding Hub",
        "slug": "wedding-hub",
        "description": "Hochzeitsplanung — Events, Gäste, Budget, Timeline.",
        "icon": "💍",
        "color": "pink",
        "category": "product",
        "tags": ["Events"],
        "port": 8093,
        "container_name": "wedding_hub_web",
        "prod_url": "https://wedding-hub.iil.pet",
        "sort_order": 45,
    },
    {
        "name": "NL2CAD",
        "slug": "cad-hub",
        "description": "CAD Hub — IFC/DXF, Brandschutz, DIN 277, GAEB-Export.",
        "icon": "📐",
        "color": "green",
        "category": "product",
        "tags": ["CAD", "AI"],
        "port": 8094,
        "container_name": "cad_hub_web",
        "prod_url": "https://nl2cad.de",
        "sort_order": 50,
    },
    {
        "name": "Prezimo",
        "slug": "pptx-hub",
        "description": "AI-assisted PPTX generation with templates.",
        "icon": "📊",
        "color": "amber",
        "category": "product",
        "tags": ["PPTX"],
        "port": 8020,
        "container_name": "pptx_hub_web",
        "prod_url": "https://prezimo.de",
        "sort_order": 55,
    },
    {
        "name": "Trading Hub",
        "slug": "trading-hub",
        "description": "Algorithmic trading signals and portfolio analysis.",
        "icon": "📈",
        "color": "green",
        "category": "product",
        "tags": ["Finance"],
        "port": 8088,
        "container_name": "trading_hub_web",
        "prod_url": "https://ai-trades.de",
        "sort_order": 60,
    },
    {
        "name": "Bieterpilot",
        "slug": "ausschreibungs-hub",
        "description": "Ausschreibungsmanagement — Vergabe, Angebote, Dokumente.",
        "icon": "📋",
        "color": "cyan",
        "category": "product",
        "tags": ["Vergabe", "SaaS"],
        "port": 8101,
        "container_name": "ausschreibungs_hub_web",
        "prod_url": "https://bieterpilot.de",
        "sort_order": 65,
    },
    {
        "name": "Tax Hub",
        "slug": "tax-hub",
        "description": "Steuerberatung SaaS — Mandanten, Bescheide, Fristen, DMS.",
        "icon": "🧾",
        "color": "green",
        "category": "product",
        "tags": ["Tax", "SaaS"],
        "port": 8099,
        "container_name": "tax_hub_web",
        "prod_url": "https://tax.iil.pet",
        "sort_order": 72,
    },
    {
        "name": "Illustration Hub",
        "slug": "illustration-hub",
        "description": "KI-gestützte Illustration — Buchcover, Szenen, Character Art.",
        "icon": "🎨",
        "color": "pink",
        "category": "product",
        "tags": ["AI", "Illustration"],
        "port": 8096,
        "container_name": "illustration_hub_web",
        "prod_url": "https://illustration.iil.pet",
        "sort_order": 73,
    },
    {
        "name": "Learn Hub",
        "slug": "learn-hub",
        "description": "Lernplattform — Kurse, Quizze, Zertifikate, SCORM, Gamification.",
        "icon": "🎓",
        "color": "accent",
        "category": "product",
        "tags": ["Learning", "LMS"],
        "port": 8100,
        "container_name": "learn_hub_web",
        "prod_url": "https://learn.iil.pet",
        "sort_order": 74,
    },
    {
        "name": "Research Hub",
        "slug": "research-hub",
        "description": "KI-Recherche — Quellen, Zusammenfassungen, RAG-Pipelines.",
        "icon": "🔬",
        "color": "cyan",
        "category": "product",
        "tags": ["Research", "AI"],
        "port": 8098,
        "container_name": "research_hub_web",
        "prod_url": "https://research.iil.pet",
        "sort_order": 75,
    },
    {
        "name": "DMS Hub",
        "slug": "dms-hub",
        "description": "Dokumentenmanagement — Upload, OCR, d.velop-Archivierung.",
        "icon": "📁",
        "color": "amber",
        "category": "internal",
        "tags": ["DMS", "d.velop"],
        "port": 8107,
        "container_name": "dms_hub_web",
        "prod_url": "https://dms.iil.pet",
        "sort_order": 76,
    },
    {
        "name": "dev-hub",
        "slug": "dev-hub",
        "description": "Developer Portal — Service Catalog, ADRs, Health Checks.",
        "icon": "🛠️",
        "color": "accent",
        "category": "internal",
        "tags": ["DevOps", "Portal"],
        "port": 8085,
        "container_name": "devhub_web",
        "prod_url": "https://devhub.iil.pet",
        "sort_order": 80,
    },
    {
        "name": "Billing Hub",
        "slug": "billing-hub",
        "description": "Central billing service — Subscriptions, Invoices, Stripe.",
        "icon": "💰",
        "color": "green",
        "category": "internal",
        "tags": ["Billing"],
        "port": 8092,
        "container_name": "billing-hub-web",
        "prod_url": "https://billing.iil.pet",
        "sort_order": 85,
    },
    {
        "name": "Recruiting Hub",
        "slug": "recruiting-hub",
        "description": "Recruiting & Bewerbermanagement — Stellen, Bewerber, Pipeline.",
        "icon": "👤",
        "color": "accent",
        "category": "internal",
        "tags": ["HR", "Recruiting"],
        "port": 8103,
        "container_name": "recruiting_hub_web",
        "sort_order": 86,
    },
]


# Compose file search order — local dev first, prod as fallback
COMPOSE_FILES = (
    "docker-compose.yml",
    "docker-compose.local.yml",
    "docker-compose.dev.yml",
    "docker-compose.prod.yml",
)


def find_compose_file(repo_path: Path) -> str | None:
    """Find the best compose file in a repo directory."""
    for cf in COMPOSE_FILES:
        if (repo_path / cf).exists():
            return cf
    return None
